[package]
name = "engine"
version = "0.1.0"
authors = ["Enigmatrix <enigmatrix2000@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full", "tracing"] }
tonic = "0.3"

winapi = { version = "0.3", features = ["everything", "impl-default", "impl-debug"] }
ntapi = { version = "0.2", features = ["user", "impl-default"] }
winrt = "0.7"
libffi = "0.9.0"
widestring = "0.4.2"

tracing = "0.1"
tracing-subscriber = "0.2"