name: main

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Windows SDK
      uses: ilammy/msvc-dev-cmd@v1.2.0
      with:
        sdk: 10.0.18362.2005
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal --logger "trx;LogFileName=TestResults.trx"
    - name: Benchmark
      run: dotnet run --project tests/Cobalt.Tests.Benchmarks/Cobalt.Tests.Benchmarks.csproj --no-restore -c Release
    - uses: actions/upload-artifact@v2
      name: Upload Benchmark Results
      with:
        name: Benchmarks
        path: .\BenchmarkDotNet.Artifacts\results\*.html
    - uses: actions/upload-artifact@v2
      name: Upload Test Results
      if: failure()
      with:
        name: Tests
        path: .\tests\Cobalt.Tests\TestResults\TestResults.trx
